export const REQUEST_TRAILS='REQUEST_TRAILS'
export const GET_TRAILS_FAILURE='GET_TRAILS_FAILURE'
export const GET_TRAILS_SUCCESS='GET_TRAILS_SUCCESS'
export const CHANGE_SELECTED_TRAIL='CHANGE_SELECTED_TRAIL'