// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrailsLookup.Models;

namespace TrailsLookup.Migrations
{
    [DbContext(typeof(TrailsLookupContext))]
    [Migration("20200503063136_updateTrailModelToIncludeMultipleConnections")]
    partial class updateTrailModelToIncludeMultipleConnections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrailsLookup.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FirstAdjoiningSegment1");

                    b.Property<int?>("FirstAdjoiningSegment2");

                    b.Property<int?>("FirstAdjoiningSegment3");

                    b.Property<int>("GeoObjNumber");

                    b.Property<double>("Miles");

                    b.Property<string>("Name");

                    b.Property<int>("SecondAdjoiningSegment1");

                    b.Property<int?>("SecondAdjoiningSegment2");

                    b.Property<int?>("SecondAdjoiningSegment3");

                    b.Property<string>("Surface");

                    b.Property<string>("Type");

                    b.HasKey("TrailId");

                    b.ToTable("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
