new Trail { TrailId = 307, GeoObjNumber = 934, Name = "White Pine Trail", Miles = 0.11685542, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 86, FirstAdjoiningSegment2 = 446, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 844, SecondAdjoiningSegment2 = 83, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 308, GeoObjNumber = 83, Name = "White Pine Trail", Miles = 0.1404957, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 934, FirstAdjoiningSegment2 = 844, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 845, SecondAdjoiningSegment2 = 840, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 309, GeoObjNumber = 844, Name = "Site Trail (HA)", Miles = 0.03189668, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 83, FirstAdjoiningSegment2 = 934, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 362, SecondAdjoiningSegment2 = 845, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 310, GeoObjNumber = 845, Name = "Bristlecone Pine Trail", Miles = 0.05346263, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 844, FirstAdjoiningSegment2 = 362, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 840, SecondAdjoiningSegment2 = 83, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 311, GeoObjNumber = 840, Name = "White Pine Trail", Miles = 0.00863413, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 845, FirstAdjoiningSegment2 = 83, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 870, SecondAdjoiningSegment2 = 698, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 312, GeoObjNumber = 698, Name = "White Pine Trail", Miles = 0.21958829, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 870, FirstAdjoiningSegment2 = 840, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 696, SecondAdjoiningSegment2 = 851, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 313, GeoObjNumber = 851, Name = "White Pine Trail", Miles = 0.06107445, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 698, FirstAdjoiningSegment2 = 696, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 978, SecondAdjoiningSegment2 = 157, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 314, GeoObjNumber = 157, Name = "White Pine Trail", Miles = 0.01247009, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 978, FirstAdjoiningSegment2 = 851, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 165, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 315, GeoObjNumber = 165, Name = "White Pine Trail", Miles = 0.03020214, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 157, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 164, SecondAdjoiningSegment2 = 167, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 316, GeoObjNumber = 167, Name = "White Pine Trail", Miles = 0.02107268, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 165, FirstAdjoiningSegment2 = 164, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 855, SecondAdjoiningSegment2 = 379, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 317, GeoObjNumber = 379, Name = "White Pine Trail", Miles = 0.05269361, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 167, FirstAdjoiningSegment2 = 855, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 381, SecondAdjoiningSegment2 = 393, SecondAdjoiningSegment3 = 215, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 318, GeoObjNumber = 215, Name = "White Pine Trail", Miles =  0.093819, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 393, FirstAdjoiningSegment2 = 381, FirstAdjoiningSegment3 = 379, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 2485, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 319, GeoObjNumber = 2485, Name = "Site Trail (HA)", Miles = 0.06062982, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 215, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 214, SecondAdjoiningSegment2 = 2479, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 320, GeoObjNumber = 2479, Name = "Wildwood Trail", Miles = 0.02552372, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 214, FirstAdjoiningSegment2 = 2485, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 2480, SecondAdjoiningSegment2 = 911, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 321, GeoObjNumber = 911, Name = "Wildwood Trail", Miles = 0.03488487, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 2480, FirstAdjoiningSegment2 = 2479, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 879, SecondAdjoiningSegment2 = 988, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 322, GeoObjNumber = 879, Name = "Site Trail (HA)", Miles = 0.03127447, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 911, FirstAdjoiningSegment2 = 988, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 878, SecondAdjoiningSegment2 = 1010, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 323, GeoObjNumber = 1010, Name = "Marquam Trail", Miles = 0.18399314, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 879, FirstAdjoiningSegment2 = 878, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1519, SecondAdjoiningSegment2 = 66, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 324, GeoObjNumber = 1519, Name = "Marquam Trail", Miles = 0.18059239, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 66, FirstAdjoiningSegment2 = 1010, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1520, SecondAdjoiningSegment2 = 2481, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 325, GeoObjNumber = 2481, Name = "Marquam Trail", Miles = 0.1158155, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 1519, FirstAdjoiningSegment2 = 1520, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 322, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 326, GeoObjNumber = 1520, Name = "Old Marquam Trail", Miles = 0.03694629, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 1, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1519, SecondAdjoiningSegment2 = 2481, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 327, GeoObjNumber = 322, Name = "Marquam Trail", Miles = 0.02679493, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 2481, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 798, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 328, GeoObjNumber = 798, Name = "SW Zoo Rd.", Miles = 0.21232584, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 322, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1012, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 329, GeoObjNumber = 1012, Name = "SW Knight Blvd.", Miles = 0.28482494, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 798, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 993, SecondAdjoiningSegment2 = 65, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 330, GeoObjNumber = 65, Name = "Site Trail (HA)", Miles = 0.04936134, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 993, FirstAdjoiningSegment2 = 1012, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 995, SecondAdjoiningSegment2 = 66, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 331, GeoObjNumber = 66, Name = "Site Trail (HA)", Miles = 0.07334222, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 65, FirstAdjoiningSegment2 = 995, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1519, SecondAdjoiningSegment2 = 1010, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 332, GeoObjNumber = 995, Name = "Site Trail (HA)", Miles = 0.01868651, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 65, FirstAdjoiningSegment2 = 66, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 590, SecondAdjoiningSegment2 = 369, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 333, GeoObjNumber = 993, Name = "SW Knight Blvd.", Miles = 0.00552158, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 1012, FirstAdjoiningSegment2 = 65, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 990, SecondAdjoiningSegment2 = 991, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 334, GeoObjNumber = 991, Name = "Site Trail (HA)", Miles = 0.01937486, Type = "staircase", Surface = "concrete", FirstAdjoiningSegment1 = 993, FirstAdjoiningSegment2 = 990, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 586, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 335, GeoObjNumber = 586, Name = "Vietnam Veterans Memorial", Miles = 0.03677427, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 991, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 590, SecondAdjoiningSegment2 = 585, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 336, GeoObjNumber = 590, Name = "Vietnam Veterans Memorial", Miles = 0.10901157, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 586, FirstAdjoiningSegment2 = 585, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 369, SecondAdjoiningSegment2 = 995, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 337, GeoObjNumber = 585, Name = "Vietnam Veterans Memorial", Miles = 0.09750854, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 586, FirstAdjoiningSegment2 = 590, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 584, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 338, GeoObjNumber = 369, Name = "Vietnam Veterans Memorial", Miles = 0.12027345, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 995, FirstAdjoiningSegment2 = 590, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 885, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 339, GeoObjNumber = 584, Name = "Site Trail (HA)", Miles = 0.01026344, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 585, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 376, SecondAdjoiningSegment2 = 371, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 340, GeoObjNumber = 990, Name = "SW Knight Blvd.", Miles = 0.03968474, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 993, FirstAdjoiningSegment2 = 991, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 375, SecondAdjoiningSegment2 = 376, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 341, GeoObjNumber = 376, Name = "Site Trail (HA)", Miles = 0.03126912, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 584, FirstAdjoiningSegment2 = 371, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 990, SecondAdjoiningSegment2 = 375, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 342, GeoObjNumber = 375, Name = "SW Knight Blvd.", Miles = 0.03510022, Type = "on-street trail", Surface = "sidewalk", FirstAdjoiningSegment1 = 990, FirstAdjoiningSegment2 = 376, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 882, SecondAdjoiningSegment2 = 880, SecondAdjoiningSegment3 = 371, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 343, GeoObjNumber = 371, Name = "Site Trail (HA)", Miles = 0.0484264, Type = "pedestrian path", Surface = "concrete", FirstAdjoiningSegment1 = 375, FirstAdjoiningSegment2 = 882, FirstAdjoiningSegment3 = 880, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 376, SecondAdjoiningSegment2 = 584, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 344, GeoObjNumber = 880, Name = "Wildwood Trail", Miles = 0.05116719, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 882, FirstAdjoiningSegment2 = 375, FirstAdjoiningSegment3 = 371, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 576, SecondAdjoiningSegment2 = 885, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 345, GeoObjNumber = 885, Name = "Site Trail (HA)", Miles = 0.05750461, Type = "pedestrian path", Surface = "gravel", FirstAdjoiningSegment1 = 576, FirstAdjoiningSegment2 = 880, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 369, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 346, GeoObjNumber = 576, Name = "Wildwood Trail", Miles = 0.0171956, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 885, FirstAdjoiningSegment2 = 880, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 910, SecondAdjoiningSegment2 = 581, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 347, GeoObjNumber = 581, Name = "Wildwood Trail", Miles = 0.04007622, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 576, FirstAdjoiningSegment2 = 910, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 878, SecondAdjoiningSegment2 = 2478, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 348, GeoObjNumber = 878, Name = "Marquam Trail", Miles = 0.05689775, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 581, FirstAdjoiningSegment2 = 2478, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 1010, SecondAdjoiningSegment2 = 879, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 349, GeoObjNumber = 2478, Name = "Wildwood Trail", Miles = 0.02392413, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 581, FirstAdjoiningSegment2 = 878, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 988, SecondAdjoiningSegment2 = 2480, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 350, GeoObjNumber = 988, Name = "Wildwood Trail", Miles = 0.03453011, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 2478, FirstAdjoiningSegment2 = 2480, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 879, SecondAdjoiningSegment2 = 911, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 351, GeoObjNumber = 2480, Name = "Site Trail (HA)", Miles = 0.05329237, Type = "Trail/Path (1-3 ft.)", Surface = "surface unknown", FirstAdjoiningSegment1 = 2478, FirstAdjoiningSegment2 = 988, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 911, SecondAdjoiningSegment2 = 2479, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 352, GeoObjNumber = 910, Name = "Maple Trail (HA)", Miles = 0.03284597, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 581, FirstAdjoiningSegment2 = 576, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 912, SecondAdjoiningSegment2 = 217, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 353, GeoObjNumber = 217, Name = "Site Trail (HA)", Miles = 0.03412131, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 910, FirstAdjoiningSegment2 = 912, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 872, SecondAdjoiningSegment2 = 214, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 354, GeoObjNumber = 214, Name = "Wildwood Trail", Miles = 0.11685533, Type = "Trail/Path (5-6 ft.)", Surface = "gravel", FirstAdjoiningSegment1 = 217, FirstAdjoiningSegment2 = 872, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 2479, SecondAdjoiningSegment2 = 2485, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 355, GeoObjNumber = 393, Name = "Maintenance Road (HA)", Miles = 0.07608152, Type = "Maintenance Road", Surface = "gravel", FirstAdjoiningSegment1 = 1, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 215, SecondAdjoiningSegment2 = 381, SecondAdjoiningSegment3 = 379, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 356, GeoObjNumber = 381, Name = "Maintenance Road (HA)", Miles = 0.05150997, Type = "Maintenance Road", Surface = "gravel", FirstAdjoiningSegment1 = 215, FirstAdjoiningSegment2 = 393, FirstAdjoiningSegment3 = 379, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 385, SecondAdjoiningSegment2 = 855, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 357, GeoObjNumber = 855, Name = "Fir Trail", Miles = 0.01196259, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 381, FirstAdjoiningSegment2 = 385, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 379, SecondAdjoiningSegment2 = 167, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 358, GeoObjNumber = 385, Name = "Fir Trail", Miles = 0.08174394, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 381, FirstAdjoiningSegment2 = 855, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 168, SecondAdjoiningSegment2 = 158, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 359, GeoObjNumber = 168, Name = "Fir Trail", Miles = 0.03981006, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 385, FirstAdjoiningSegment2 = 158, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 854, SecondAdjoiningSegment2 = 320, SecondAdjoiningSegment3 = 321, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 360, GeoObjNumber = 158, Name = "Redwood Trail", Miles = 0.0837946, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 385, FirstAdjoiningSegment2 = 168, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 852, SecondAdjoiningSegment2 = 154, SecondAdjoiningSegment3 = 164, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 361, GeoObjNumber = 164, Name = "Fir Trail", Miles = 0.03112009, Type = "Maintenance Road", Surface = "gravel", FirstAdjoiningSegment1 = 158, FirstAdjoiningSegment2 = 852, FirstAdjoiningSegment3 = 154, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 167, SecondAdjoiningSegment2 = 165, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 362, GeoObjNumber = 852, Name = "Fir Trail", Miles = 0.0220201, Type = "Maintenance Road", Surface = "gravel", FirstAdjoiningSegment1 = 0, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 158, SecondAdjoiningSegment2 = 164, SecondAdjoiningSegment3 = 154, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 363, GeoObjNumber = 154, Name = "Redwood Trail", Miles = 0.10303841, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 972, FirstAdjoiningSegment2 = 699, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 852, SecondAdjoiningSegment2 = 158, SecondAdjoiningSegment3 = 164, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 364, GeoObjNumber = 972, Name = "Site Trail (HA)", Miles = 0.03842098, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 1, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 154, SecondAdjoiningSegment2 = 699, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 365, GeoObjNumber = 699, Name = "Redwood Trail", Miles = 0.09908254, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 972, FirstAdjoiningSegment2 = 154, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 252, SecondAdjoiningSegment2 = 363, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 366, GeoObjNumber = 252, Name = "Site Trail (HA)", Miles = 0.02487517, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 699, FirstAdjoiningSegment2 = 363, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 251, SecondAdjoiningSegment2 = 969, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 367, GeoObjNumber = 969, Name = "Creek Trail", Miles = 0.08942465, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 252, FirstAdjoiningSegment2 = 251, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 2488, SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 368, GeoObjNumber = 2488, Name = "Bristlecone Pine Trail", Miles = 0.01185471, Type = "Trail/Path (1-3 ft.)", Surface = "soil", FirstAdjoiningSegment1 = 969, FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 978, SecondAdjoiningSegment2 = 247, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 369, GeoObjNumber = 247, Name = "Bristlecone Pine Trail", Miles = 0.11201296, Type = "pedestrian path", Surface = "asphalt", FirstAdjoiningSegment1 = 978, FirstAdjoiningSegment2 = 2488, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 253, SecondAdjoiningSegment2 = 248, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 370, GeoObjNumber = 253, Name = "Bristlecone Pine Trail", Miles = 0.04264067, Type = "pedestrian path", Surface = "asphalt", FirstAdjoiningSegment1 = 247, FirstAdjoiningSegment2 = 248, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 694, SecondAdjoiningSegment2 = 692, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 371, GeoObjNumber = 694, Name = "Bristlecone Pine Trail", Miles = 0.04434757, Type = "pedestrian path", Surface = "asphalt", FirstAdjoiningSegment1 = 692, FirstAdjoiningSegment2 = 253, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 692, SecondAdjoiningSegment2 = 696, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },
new Trail { TrailId = 372, GeoObjNumber = 692, Name = "Bristlecone Pine Trail", Miles = 0.02631028, Type = "pedestrian path", Surface = "asphalt", FirstAdjoiningSegment1 = 253, FirstAdjoiningSegment2 = 694, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = 696, SecondAdjoiningSegment2 = 694, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 373, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 374, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 375, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 376, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 377, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 378, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 379, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 380, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 381, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 382, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 383, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 384, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 385, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 386, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 387, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 388, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 389, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 390, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 391, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 392, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 393, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 394, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 395, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = 396, GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },

new Trail { TrailId = , GeoObjNumber = , Name = "", Miles = , Type = "", Surface = "", FirstAdjoiningSegment1 = , FirstAdjoiningSegment2 = null, FirstAdjoiningSegment3 = null, FirstAdjoiningSegment4 = null, SecondAdjoiningSegment1 = , SecondAdjoiningSegment2 = null, SecondAdjoiningSegment3 = null, SecondAdjoiningSegment4 = null },